package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/masahide/fastpass/models"
)

/*DeleteEventNoContent イベント削除

swagger:response deleteEventNoContent
*/
type DeleteEventNoContent struct {
}

// NewDeleteEventNoContent creates DeleteEventNoContent with default headers values
func NewDeleteEventNoContent() *DeleteEventNoContent {
	return &DeleteEventNoContent{}
}

// WriteResponse to the client
func (o *DeleteEventNoContent) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(204)
}

/*DeleteEventInternalServerError unexpected error

swagger:response deleteEventInternalServerError
*/
type DeleteEventInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteEventInternalServerError creates DeleteEventInternalServerError with default headers values
func NewDeleteEventInternalServerError() *DeleteEventInternalServerError {
	return &DeleteEventInternalServerError{}
}

// WithPayload adds the payload to the delete event internal server error response
func (o *DeleteEventInternalServerError) WithPayload(payload *models.Error) *DeleteEventInternalServerError {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DeleteEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
