package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/masahide/fastpass/models"
)

/*ListEventsOK 一覧取得成功

swagger:response listEventsOK
*/
type ListEventsOK struct {

	// In: body
	Payload []*models.Event `json:"body,omitempty"`
}

// NewListEventsOK creates ListEventsOK with default headers values
func NewListEventsOK() *ListEventsOK {
	return &ListEventsOK{}
}

// WithPayload adds the payload to the list events o k response
func (o *ListEventsOK) WithPayload(payload []*models.Event) *ListEventsOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *ListEventsOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListEventsInternalServerError unexpected error

swagger:response listEventsInternalServerError
*/
type ListEventsInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewListEventsInternalServerError creates ListEventsInternalServerError with default headers values
func NewListEventsInternalServerError() *ListEventsInternalServerError {
	return &ListEventsInternalServerError{}
}

// WithPayload adds the payload to the list events internal server error response
func (o *ListEventsInternalServerError) WithPayload(payload *models.Error) *ListEventsInternalServerError {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *ListEventsInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
